"""Core activation grafting engine."""

from enum import Enum
from typing import Optional, Dict, List, Tuple, Union, Any
from dataclasses import dataclass, asdict
import torch
from torch import Tensor
from torch import nn
from transformers import PreTrainedModel, PreTrainedTokenizer

from src.models.activation_extractor import (
    ActivationExtractor,
    ExtractionPoint,
)
from src.models.layer_utils import (
    get_transformer_layers,
    unpack_hook_output,
    repack_hook_output,
)
from src.models.inference_utils import generate_response, extract_activation
from src.communication.combination_functions import CombinationFunction
from src.tokenization.alignment import TokenizerAligner


class GraftingMode(Enum):
    """
    Strategy for activation grafting during multi-token generation.

    SINGLE_SHOT: Graft A's activation only on the first forward pass.
                 Subsequent tokens are generated by B alone.
                 Most efficient, tests if initial activation transfer is sufficient.

    CACHED: Extract A's activation once, reuse for all generation steps.
            The grafted activation influences each generated token.
            Balance between cost and continuous influence.

    CONTINUOUS: Re-extract from A on every generation step.
                Most faithful to continuous communication but expensive.
                Note: Requires A to also generate in parallel.
    """

    SINGLE_SHOT = "single_shot"
    CACHED = "cached"
    CONTINUOUS = "continuous"


@dataclass
class GraftingDiagnostics:
    """Diagnostic information from a grafting operation."""

    # Activation norms
    activation_a_norm: float
    activation_b_norm: float
    combined_norm: float

    # Similarity metrics
    cosine_similarity_ab: float
    cosine_similarity_combined_b: float  # cosine sim between combined activation and target activation_b
    l2_distance_source_target: float     # L2 distance between combined (source) and target activation_b

    # Output distribution
    output_entropy: float
    top_token: str
    top_token_prob: float

    # Configuration
    layer_a: int
    layer_b: int
    grafting_mode: str
    extraction_point: str

    # Positions
    graft_position: int
    sequence_length_a: int
    sequence_length_b: int

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class ActivationGraftingEngine:
    """
    Core engine for activation grafting between two models.

    This class orchestrates:
    1. Running Model A to extract activations
    2. Running Model B with grafted activations
    3. Generation with various grafting strategies

    The grafting process:
    1. Run Model A on prompt_a, extract activation at layer_a
    2. Run Model B on prompt_b, at layer_b:
       - Get B's activation at the graft position
       - Combine with A's activation using combination_fn
       - Replace B's activation with the combined result
    3. Continue B's forward pass and generate output
    """

    def __init__(
        self,
        model_a: PreTrainedModel,
        model_b: PreTrainedModel,
        tokenizer_a: PreTrainedTokenizer,
        tokenizer_b: PreTrainedTokenizer,
        layer_a: int,
        layer_b: int,
        combination_fn: CombinationFunction,
        extraction_point: ExtractionPoint = ExtractionPoint.POST_MLP,
        grafting_mode: GraftingMode = GraftingMode.SINGLE_SHOT,
        dry_run: bool = False,
        graft_position: int = -1,
    ):
        """
        Initialize the grafting engine.

        Args:
            model_a: Model A (sender/source of activations)
            model_b: Model B (receiver/target for grafting)
            tokenizer_a: Tokenizer for Model A
            tokenizer_b: Tokenizer for Model B
            layer_a: Layer index to extract from in Model A
            layer_b: Layer index to inject into in Model B
            combination_fn: Function to combine activations
            extraction_point: Where in the layer to extract/inject
            grafting_mode: Strategy for multi-token generation
            dry_run: If True, the hook fires and computes the combined
                activation (for diagnostics/cosine-sim logging) but does
                NOT write it back — model B runs unmodified.
            graft_position: Token position in prompt_b to graft at.
                0 = first token, -1 = last token (default), -2 = penultimate.
        """
        self.model_a = model_a
        self.model_b = model_b
        self.tokenizer_a = tokenizer_a
        self.tokenizer_b = tokenizer_b
        self.layer_a = layer_a
        self.layer_b = layer_b
        self.combination_fn = combination_fn
        self.extraction_point = extraction_point
        self.grafting_mode = grafting_mode
        self.dry_run = dry_run
        self.graft_position = graft_position

        # Get device from model B (where we'll inject)
        self.device = next(model_b.parameters()).device

        # Move combination function to device
        self.combination_fn.to(self.device)

        # Tokenizer alignment (skipped when model_a is None / random source)
        if tokenizer_a is not None:
            self.aligner = TokenizerAligner(tokenizer_a, tokenizer_b)
        else:
            self.aligner = None

        # Validate configuration
        self._validate_config()

        # State for grafting
        self._cached_activation_a: Optional[Tensor] = None

    def _validate_config(self) -> None:
        """Validate configuration is sensible."""
        # Check layer indices
        n_layers_b = self.model_b.config.num_hidden_layers
        if self.model_a is not None:
            n_layers_a = self.model_a.config.num_hidden_layers
            if self.layer_a < 0 or self.layer_a >= n_layers_a:
                raise ValueError(
                    f"layer_a={self.layer_a} out of range [0, {n_layers_a})"
                )
        if self.layer_b < 0 or self.layer_b >= n_layers_b:
            raise ValueError(
                f"layer_b={self.layer_b} out of range [0, {n_layers_b})"
            )

        # Warn about tokenizer mismatch
        if self.aligner is not None and not self.aligner.is_identical:
            import warnings  # pylint: disable=import-outside-toplevel
            warnings.warn(
                "Tokenizers differ between Model A and B. "
                "Token alignment may be imperfect."
            )

    def _extract_from_a(
        self,
        prompt_a: str,
        max_length: int = 512,
    ) -> Tuple[Tensor, int]:
        """
        Extract activation from Model A.

        Args:
            prompt_a: Input prompt for Model A
            max_length: Maximum sequence length

        Returns:
            Tuple of (activation tensor [1, d_a], sequence length)
        """
        if self.model_a is None:
            # Random source: return a dummy tensor (ignored by RandomNoiseCombination)
            return torch.zeros(1, 1, device=self.device), 0
        return extract_activation(
            self.model_a, self.tokenizer_a, prompt_a,
            self.layer_a, self.extraction_point, self.device,
            max_length=max_length,
        )

    def _get_b_activation(
        self,
        input_ids: Tensor,
        attention_mask: Optional[Tensor] = None,
    ) -> Tensor:
        """
        Get Model B's activation at the graft layer (without grafting).

        Args:
            input_ids: Input token IDs for Model B
            attention_mask: Attention mask

        Returns:
            Activation tensor [batch, d_b]
        """
        extractor = ActivationExtractor(
            self.model_b,
            [self.layer_b],
            self.extraction_point,
            token_position=-1,
        )

        with torch.no_grad():
            activations = extractor.extract(input_ids, attention_mask)

        return activations[self.layer_b].tensor

    def _create_grafting_hook(
        self,
        activation_a: Tensor,
        graft_position: int = -1,
    ):
        """
        Create a forward hook that performs activation grafting.

        In SINGLE_SHOT mode, the hook fires only on the first forward pass
        (the prefill pass) and is a no-op on subsequent autoregressive steps.
        In CACHED/CONTINUOUS modes, the hook fires on every forward pass.

        Args:
            activation_a: Activation from Model A [batch, d_a]
            graft_position: Token position to graft at (-1 for last)

        Returns:
            Hook function
        """
        combination_fn = self.combination_fn
        grafting_mode = self.grafting_mode
        dry_run = self.dry_run
        fired = [False]

        def hook(_module, _input, output):
            # In SINGLE_SHOT mode, only graft during the first forward pass
            # (the prefill). Subsequent autoregressive steps are unmodified.
            if grafting_mode == GraftingMode.SINGLE_SHOT and fired[0]:
                return output
            fired[0] = True

            # In dry_run mode the hook fires (marking it as fired for SINGLE_SHOT)
            # but leaves model B's hidden states untouched.
            if dry_run:
                return output

            hidden_states, rest = unpack_hook_output(output)

            # Determine position
            seq_len = hidden_states.shape[1]
            pos = graft_position
            if pos < 0:
                pos = seq_len + pos

            if pos < 0 or pos >= seq_len:
                # Position out of range, skip grafting
                return output

            # Combine activations (full hidden_states passed for context-aware strategies)
            combined = combination_fn.combine_with_context(activation_a, hidden_states, pos)

            # Clone to avoid in-place modification issues
            hidden_states = hidden_states.clone()
            hidden_states[:, pos, :] = combined

            return repack_hook_output(hidden_states, rest)

        return hook

    def _get_target_layer(self) -> nn.Module:
        """Get the target layer module for hooking."""
        layers = get_transformer_layers(self.model_b)
        return layers[self.layer_b]

    def generate(
        self,
        prompt_a: str,
        prompt_b: str,
        max_new_tokens: int = 50,
        return_diagnostics: bool = False,
        return_output_scores: bool = False,
        **generation_kwargs,
    ) -> Union[str, Tuple]:
        """
        Generate text with activation grafting.

        Args:
            prompt_a: Context/prompt for Model A (sender)
            prompt_b: Context/prompt for Model B (receiver)
            max_new_tokens: Maximum tokens to generate
            return_diagnostics: If True, return diagnostics alongside output
            **generation_kwargs: Additional args for model.generate()

        Returns:
            Generated text, optionally with diagnostics
        """
        # Extract activation from A
        activation_a, seq_len_a = self._extract_from_a(prompt_a)

        # Tokenize prompt for B
        inputs_b = self.tokenizer_b(
            prompt_b,
            return_tensors="pt",
            truncation=True,
        ).to(self.device)

        seq_len_b = inputs_b["input_ids"].shape[1]

        # Get B's original activation for diagnostics
        if return_diagnostics:
            activation_b = self._get_b_activation(
                inputs_b["input_ids"],
                inputs_b.get("attention_mask"),
            )

        # Setup default generation kwargs
        gen_kwargs = {
            "max_new_tokens": max_new_tokens,
            "pad_token_id": self.tokenizer_b.pad_token_id or self.tokenizer_b.eos_token_id,
            "do_sample": False,
        }
        gen_kwargs.update(generation_kwargs)
        if return_output_scores:
            gen_kwargs["output_scores"] = True
            gen_kwargs["return_dict_in_generate"] = True

        # Create and register hook
        hook = self._create_grafting_hook(activation_a, self.graft_position)
        target_layer = self._get_target_layer()

        hook_handle = target_layer.register_forward_hook(hook)

        # Register extra capture hook on layer_b-1 for PrevLayerActivationCombination
        capture_hook_handle = None
        if hasattr(self.combination_fn, 'make_capture_hook'):
            layers = get_transformer_layers(self.model_b)
            prev_layer = layers[max(0, self.layer_b - 1)]
            capture_hook_handle = prev_layer.register_forward_hook(
                self.combination_fn.make_capture_hook(self.graft_position)
            )

        try:
            # Cache activation for non-single-shot modes
            if self.grafting_mode != GraftingMode.SINGLE_SHOT:
                self._cached_activation_a = activation_a

            with torch.no_grad():
                outputs = self.model_b.generate(
                    **inputs_b,
                    **gen_kwargs,
                )

            self._cached_activation_a = None

        finally:
            # Always remove hooks
            hook_handle.remove()
            if capture_hook_handle is not None:
                capture_hook_handle.remove()

        # Handle GenerateOutput vs plain tensor (when return_dict_in_generate=True)
        output_scores_tuple = None
        if hasattr(outputs, 'sequences'):
            output_scores_tuple = getattr(outputs, 'scores', None)
            outputs = outputs.sequences

        # Decode output (remove prompt tokens)
        generated_ids = outputs[0][inputs_b["input_ids"].shape[1]:]
        generated_text = self.tokenizer_b.decode(
            generated_ids, skip_special_tokens=True
        )

        if return_diagnostics:
            # Compute diagnostics
            with torch.no_grad():
                # combine_with_context with a single-token hidden_states at pos=0
                combined = self.combination_fn.combine_with_context(
                    activation_a, activation_b.unsqueeze(1), 0
                )

                # Get output distribution for entropy
                logits = self.model_b(**inputs_b).logits[0, -1, :]
                probs = torch.softmax(logits, dim=-1)
                entropy = -torch.sum(probs * torch.log(probs + 1e-10)).item()

                # Top token
                top_idx = probs.argmax().item()
                top_token = self.tokenizer_b.decode([top_idx])
                top_prob = probs[top_idx].item()

            diagnostics = GraftingDiagnostics(
                activation_a_norm=activation_a.norm().item(),
                activation_b_norm=activation_b.norm().item(),
                combined_norm=combined.norm().item(),
                cosine_similarity_ab=(
                    torch.nn.functional.cosine_similarity(
                        activation_a.flatten(),
                        activation_b.flatten(),
                        dim=0,
                    ).item()
                    if activation_a.numel() == activation_b.numel()
                    else float('nan')
                ),
                cosine_similarity_combined_b=torch.nn.functional.cosine_similarity(
                    combined.flatten(),
                    activation_b.flatten(),
                    dim=0,
                ).item(),
                l2_distance_source_target=(combined - activation_b).norm().item(),
                output_entropy=entropy,
                top_token=top_token,
                top_token_prob=top_prob,
                layer_a=self.layer_a,
                layer_b=self.layer_b,
                grafting_mode=self.grafting_mode.value,
                extraction_point=self.extraction_point.value,
                graft_position=(self.graft_position if self.graft_position >= 0 else seq_len_b + self.graft_position),
                sequence_length_a=seq_len_a,
                sequence_length_b=seq_len_b,
            )

            if return_output_scores:
                return generated_text, diagnostics, output_scores_tuple, generated_ids
            return generated_text, diagnostics

        if return_output_scores:
            return generated_text, output_scores_tuple, generated_ids
        return generated_text

    def forward_with_graft(
        self,
        prompt_a: str,
        prompt_b: str,
    ) -> Tuple[Tensor, GraftingDiagnostics]:
        """
        Run a single forward pass with grafting (no generation).

        Useful for analysis and debugging.

        Args:
            prompt_a: Prompt for Model A
            prompt_b: Prompt for Model B

        Returns:
            Tuple of (logits, diagnostics)
        """
        # Extract from A
        activation_a, seq_len_a = self._extract_from_a(prompt_a)

        # Tokenize for B
        inputs_b = self.tokenizer_b(
            prompt_b,
            return_tensors="pt",
            truncation=True,
        ).to(self.device)

        seq_len_b = inputs_b["input_ids"].shape[1]

        # Get B's original activation
        activation_b = self._get_b_activation(
            inputs_b["input_ids"],
            inputs_b.get("attention_mask"),
        )

        # Setup and register hook
        hook = self._create_grafting_hook(activation_a, self.graft_position)
        target_layer = self._get_target_layer()
        hook_handle = target_layer.register_forward_hook(hook)

        try:
            with torch.no_grad():
                outputs = self.model_b(**inputs_b)
        finally:
            hook_handle.remove()

        # Compute diagnostics
        combined = self.combination_fn.combine_with_context(
            activation_a, activation_b.unsqueeze(1), 0
        )

        logits = outputs.logits[0, -1, :]
        probs = torch.softmax(logits, dim=-1)
        entropy = -torch.sum(probs * torch.log(probs + 1e-10)).item()

        top_idx = probs.argmax().item()
        top_token = self.tokenizer_b.decode([top_idx])
        top_prob = probs[top_idx].item()

        diagnostics = GraftingDiagnostics(
            activation_a_norm=activation_a.norm().item(),
            activation_b_norm=activation_b.norm().item(),
            combined_norm=combined.norm().item(),
            cosine_similarity_ab=torch.nn.functional.cosine_similarity(
                activation_a.flatten(),
                activation_b.flatten(),
                dim=0,
            ).item(),
            cosine_similarity_combined_b=torch.nn.functional.cosine_similarity(
                combined.flatten(),
                activation_b.flatten(),
                dim=0,
            ).item(),
            l2_distance_source_target=(combined - activation_b).norm().item(),
            output_entropy=entropy,
            top_token=top_token,
            top_token_prob=top_prob,
            layer_a=self.layer_a,
            layer_b=self.layer_b,
            grafting_mode=self.grafting_mode.value,
            extraction_point=self.extraction_point.value,
            graft_position=seq_len_b - 1,
            sequence_length_a=seq_len_a,
            sequence_length_b=seq_len_b,
        )

        return outputs.logits, diagnostics

    def generate_baseline(
        self,
        prompt_b: str,
        max_new_tokens: int = 50,
        **generation_kwargs,
    ) -> str:
        """
        Generate from Model B without grafting (baseline).

        Args:
            prompt_b: Prompt for Model B
            max_new_tokens: Maximum tokens to generate
            **generation_kwargs: Additional generation args

        Returns:
            Generated text
        """
        return generate_response(
            self.model_b, self.tokenizer_b, prompt_b,
            max_new_tokens, self.device, **generation_kwargs,
        )


def create_grafting_engine(
    model_a: PreTrainedModel,
    model_b: PreTrainedModel,
    tokenizer_a: PreTrainedTokenizer,
    tokenizer_b: PreTrainedTokenizer,
    layer_a: int,
    layer_b: int,
    combination_fn_name: str = "sum",
    extraction_point: str = "POST_MLP",
    grafting_mode: str = "SINGLE_SHOT",
    **combination_kwargs,
) -> ActivationGraftingEngine:
    """
    Factory function to create a grafting engine.

    Args:
        model_a: Model A (sender)
        model_b: Model B (receiver)
        tokenizer_a: Tokenizer for A
        tokenizer_b: Tokenizer for B
        layer_a: Extraction layer for A
        layer_b: Injection layer for B
        combination_fn_name: Name of combination function
        extraction_point: Where to extract/inject
        grafting_mode: Generation strategy
        **combination_kwargs: Additional args for combination function

    Returns:
        Configured ActivationGraftingEngine
    """
    from src.communication.combination_functions import get_combination_function  # pylint: disable=import-outside-toplevel
    from src.models.model_registry import get_model_spec, MODEL_REGISTRY  # pylint: disable=import-outside-toplevel

    # Get dimensions
    model_a_name = getattr(model_a.config, "_name_or_path", "")
    model_b_name = getattr(model_b.config, "_name_or_path", "")

    if model_a_name in MODEL_REGISTRY:
        d_a = get_model_spec(model_a_name).d_model
    else:
        d_a = model_a.config.hidden_size

    if model_b_name in MODEL_REGISTRY:
        d_b = get_model_spec(model_b_name).d_model
    else:
        d_b = model_b.config.hidden_size

    # Create combination function
    combination_fn = get_combination_function(
        combination_fn_name, d_a, d_b, **combination_kwargs
    )

    # Parse enums
    extraction_point_enum = ExtractionPoint[extraction_point]
    grafting_mode_enum = GraftingMode[grafting_mode]

    return ActivationGraftingEngine(
        model_a=model_a,
        model_b=model_b,
        tokenizer_a=tokenizer_a,
        tokenizer_b=tokenizer_b,
        layer_a=layer_a,
        layer_b=layer_b,
        combination_fn=combination_fn,
        extraction_point=extraction_point_enum,
        grafting_mode=grafting_mode_enum,
    )


class MultiSourceActivationGraftingEngine:
    """
    Activation grafting engine with multiple source models.

    Extracts activations from N source models, projects each to the
    target dimension, fuses them according to fusion_method, then
    writes the result into model B according to combination:
      - "replace": hidden_states[:, pos, :] = fused
      - "sum":     hidden_states[:, pos, :] = b + fused

    When N=1, this is identical to ActivationGraftingEngine.
    """

    FUSION_METHODS = {"mean", "norm_weighted", "reverse_norm_weighted", "similarity_weighted", "dissimilarity_weighted", "orthogonal_mean", "orthogonal_projection"}
    COMBINATION_MODES = {"replace", "sum"}

    def __init__(
        self,
        source_models: List[PreTrainedModel],
        model_b: PreTrainedModel,
        source_tokenizers: List[PreTrainedTokenizer],
        tokenizer_b: PreTrainedTokenizer,
        source_layers: List[int],
        layer_b: int,
        combination_fns: List[CombinationFunction],
        extraction_point: ExtractionPoint = ExtractionPoint.POST_MLP,
        grafting_mode: GraftingMode = GraftingMode.SINGLE_SHOT,
        fusion_method: str = "mean",
        combination: str = "replace",
        dry_run: bool = False,
        graft_position: int = -1,
        top_k: int = 1,
        routing: str = "none",
        routing_threshold: float = 0.0,
    ):
        """
        Args:
            source_models: List of source models (senders)
            model_b: Target model (receiver)
            source_tokenizers: Tokenizers for each source model
            tokenizer_b: Tokenizer for the target model
            source_layers: Layer index to extract from each source model
            layer_b: Layer index to inject into the target model
            combination_fns: One combination function per source model
            extraction_point: Where in the layer to extract/inject
            grafting_mode: Strategy for multi-token generation
            fusion_method: How to merge the N projected source activations into one.
                "mean": simple average (default)
                "norm_weighted": weight by L2 norm of each projected activation
                "reverse_norm_weighted": weight inversely by L2 norm
                "similarity_weighted": weight by cosine similarity to target activation b
                "dissimilarity_weighted": weight by (1 - cosine similarity) to b
            combination: How to write the fused activation into model B.
                "replace": hidden_states[:, pos, :] = fused  (default)
                "sum":     hidden_states[:, pos, :] = b + fused
            dry_run: If True, the hook computes the combined activation and
                logs cosine similarity but does NOT write back — model B runs
                unmodified.
            graft_position: Token position in prompt_b to graft at.
                0 = first token, -1 = last token (default), -2 = penultimate.
            top_k: Number of top-scoring sources to select after routing.
                Sources are ranked by their routing score; only the top-k are
                passed to the fusion step.  Applies to prototype, residual,
                norm_ratio, and residual_norm routing.  Default: 1.
            routing: Source selection strategy.
                "none": use all sources (default).
                "prototype": rank by cosine similarity to per-source prototype
                    (requires compute_prototypes() to be called first).
                "residual": rank by normalised orthogonal delta magnitude
                    ||Δ_ortho|| / ||h_target||, where Δ_ortho is the component
                    of (h_proj - h_target) orthogonal to h_target.
                "norm_ratio": rank by closeness of projected norm to target norm,
                    score = 1 / (1 + |ratio - 1|) where ratio = ||h_proj|| / ||h_target||.
                "residual_norm": product of residual and norm_ratio scores.
                "entropy": gate on target model uncertainty at the graft layer.
                    Computes entropy of the probed output distribution (final
                    LayerNorm + LM head applied to h_target at layer_b).  If
                    entropy < routing_threshold the target activation is left
                    unchanged (no-replace); otherwise all sources are grafted.
                    No per-source selection — use with top_k=all or fusion.
                "entropy_prototype": entropy gate (as above) combined with
                    prototype routing for source selection.  Requires
                    compute_prototypes() to be called first (same as
                    routing="prototype").
            routing_threshold: Minimum routing score for a source to be eligible.
                Sources scoring below this are excluded.  If no source clears the
                threshold the target activation is left unchanged (no-replace).
                Used with residual, norm_ratio, residual_norm, and entropy routing.
                For entropy routing: minimum entropy required to allow grafting
                (high-confidence inputs are skipped).
                Default: 0.0 (all sources always eligible).
        """
        assert len(source_models) == len(source_tokenizers), \
            "source_models and source_tokenizers must have the same length"
        assert len(source_models) == len(source_layers), \
            "source_models and source_layers must have the same length"
        assert len(source_models) == len(combination_fns), \
            "source_models and combination_fns must have the same length"
        assert fusion_method in self.FUSION_METHODS, \
            f"fusion_method must be one of {self.FUSION_METHODS}, got '{fusion_method}'"
        assert combination in self.COMBINATION_MODES, \
            f"combination must be one of {self.COMBINATION_MODES}, got '{combination}'"

        self.source_models = source_models
        self.model_b = model_b
        self.source_tokenizers = source_tokenizers
        self.tokenizer_b = tokenizer_b
        self.source_layers = source_layers
        self.layer_b = layer_b
        self.combination_fns = combination_fns
        self.extraction_point = extraction_point
        self.grafting_mode = grafting_mode
        self.fusion_method = fusion_method
        self.combination = combination
        self.dry_run = dry_run
        self.graft_position = graft_position
        self.top_k = top_k
        self.routing = routing
        self.routing_threshold = routing_threshold
        self.device = next(model_b.parameters()).device

        # Entropy routing: cache references to final LayerNorm and LM head
        try:
            self._lm_norm = model_b.model.norm
            self._lm_head = model_b.lm_head
        except AttributeError:
            self._lm_norm = None
            self._lm_head = None

        for fn in self.combination_fns:
            fn.to(self.device)

        self.weight_log: List[Tensor] = []
        self.cosine_sim_log: List[float] = []   # cosine sim between fused source and target per forward pass
        self.l2_dist_log: List[float] = []      # L2 distance between fused source and target activation
        self.source_norm_log: List[float] = []  # L2 norm of fused source activation
        self.target_norm_log: List[float] = []  # L2 norm of target activation

        # Prototype routing (populated by compute_prototypes())
        self.prototypes: Optional[List[Optional[Tensor]]] = None
        self.prototype_sim_log: List[List[float]] = []   # per-example cosine sims to prototypes [N]
        self.selected_source_log: List[List[int]] = []   # per-example selected source indices

        # Residual / norm_ratio routing logs
        self.routing_scores_log: List[List[float]] = []  # per-example routing scores [N]
        self.no_replace_count: int = 0                   # examples where no source cleared threshold

        # Entropy routing log
        self.entropy_log: List[float] = []  # per-example entropy of probed target distribution

    def _extract_from_sources(
        self,
        prompts_a: List[str],
        max_length: int = 512,
    ) -> List[Tensor]:
        """
        Extract activations from all source models.

        Args:
            prompts_a: One prompt per source model (same question, different tokenizers)
            max_length: Maximum sequence length

        Returns:
            List of activation tensors, one per source [1, d_a]
        """
        activations = []
        for model, tokenizer, layer, prompt in zip(
            self.source_models, self.source_tokenizers, self.source_layers, prompts_a
        ):
            if model is None:
                # Random source: return None (combination_fn handles it)
                activations.append(None)
            else:
                activation, _ = extract_activation(
                    model, tokenizer, prompt,
                    layer, self.extraction_point, self.device,
                    max_length=max_length,
                )
                activations.append(activation)
        return activations

    def compute_prototypes(
        self,
        calibration_prompts_per_source: List[List[str]],
        max_length: int = 512,
    ) -> None:
        """
        Compute a mean activation prototype for each source model from calibration prompts.

        The prototype is the average of layer_a activations over the calibration set,
        computed in source space (pre-projection).  It is used by prototype routing to
        measure how "familiar" a test input looks to each source model.

        Call this once before evaluation when routing="prototype".

        Args:
            calibration_prompts_per_source: List of N lists; each inner list contains
                the raw text prompts for the corresponding source model.
            max_length: Maximum token length for each calibration prompt.
        """
        from tqdm import tqdm as _tqdm  # pylint: disable=import-outside-toplevel
        prototypes: List[Optional[Tensor]] = []
        for i, (model, tokenizer, layer, calib_prompts) in enumerate(zip(
            self.source_models, self.source_tokenizers, self.source_layers, calibration_prompts_per_source
        )):
            if model is None or not calib_prompts:
                prototypes.append(None)
                continue
            acts = []
            for prompt in _tqdm(calib_prompts, desc=f"Prototype source {i}", leave=False):
                act, _ = extract_activation(
                    model, tokenizer, prompt, layer,
                    self.extraction_point, self.device, max_length=max_length,
                )
                acts.append(act.squeeze(0))  # [d_a]
            proto = torch.stack(acts).mean(dim=0)  # [d_a]
            prototypes.append(proto)
        self.prototypes = prototypes

    def _compute_prototype_similarities(
        self,
        source_activations: List[Optional[Tensor]],
    ) -> List[float]:
        """
        Return cosine similarity of each source's per-example activation to its prototype.

        Similarities are computed in source space (pre-projection).
        Returns a list of N floats; -1.0 is returned for sources with no prototype.
        """
        assert self.prototypes is not None, \
            "compute_prototypes() must be called before _compute_prototype_similarities()"
        sims: List[float] = []
        for act, proto in zip(source_activations, self.prototypes):
            if act is None or proto is None:
                sims.append(-1.0)
            else:
                sim = torch.nn.functional.cosine_similarity(
                    act.flatten(),
                    proto.flatten().to(act.device),
                    dim=0,
                    eps=1e-8,
                ).item()
                sims.append(sim)
        return sims

    def _create_multisource_hook(
        self,
        source_activations: List[Tensor],
        graft_position: int = -1,
        prototype_sims: Optional[List[float]] = None,
        top_k: Optional[int] = None,
    ):
        """
        Create a forward hook that averages projected source activations
        and replaces the target model's activation at the graft position.

        Args:
            source_activations: List of activations from source models
            graft_position: Token position to graft at (-1 for last)

        Returns:
            Hook function
        """
        combination_fns = self.combination_fns
        grafting_mode = self.grafting_mode
        fusion_method = self.fusion_method
        combination = self.combination
        dry_run = self.dry_run
        weight_log = self.weight_log
        cosine_sim_log = self.cosine_sim_log
        l2_dist_log = self.l2_dist_log
        source_norm_log = self.source_norm_log
        target_norm_log = self.target_norm_log
        selected_source_log = self.selected_source_log
        _top_k = top_k  # local alias (avoids shadowing self)
        _n_total_sources = len(source_activations)
        _routing = self.routing
        _routing_threshold = self.routing_threshold
        routing_scores_log = self.routing_scores_log
        entropy_log = self.entropy_log
        _lm_norm = self._lm_norm
        _lm_head = self._lm_head
        _self = self  # captured for no_replace_count increment
        fired = [False]

        def hook(_module, _input, output):
            if grafting_mode == GraftingMode.SINGLE_SHOT and fired[0]:
                return output
            fired[0] = True

            hidden_states, rest = unpack_hook_output(output)

            seq_len = hidden_states.shape[1]
            pos = graft_position
            if pos < 0:
                pos = seq_len + pos

            if pos < 0 or pos >= seq_len:
                return output

            # Project each source activation to target dimension
            activation_b = hidden_states[:, pos, :]
            projected = []
            for activation_a, combination_fn in zip(source_activations, combination_fns):
                proj = combination_fn.combine_with_context(activation_a, hidden_states, pos)
                projected.append(proj)

            # ------------------------------------------------------------------
            # Residual / norm_ratio routing: score and select sources
            # ------------------------------------------------------------------
            if _routing in ("residual", "norm_ratio", "residual_norm"):
                b_norm = activation_b.norm(dim=-1, keepdim=True).clamp(min=1e-8)  # [batch, 1]
                b_unit = activation_b / b_norm                                     # [batch, d]
                scores = []
                for proj in projected:
                    if _routing in ("residual", "residual_norm"):
                        delta = proj - activation_b
                        delta_para = (delta * b_unit).sum(dim=-1, keepdim=True) * b_unit
                        delta_ortho = delta - delta_para
                        ortho_score = (delta_ortho.norm(dim=-1) / b_norm.squeeze(-1)).mean().item()
                    else:
                        ortho_score = 1.0
                    if _routing in ("norm_ratio", "residual_norm"):
                        ratio = (proj.norm(dim=-1).mean() / (activation_b.norm(dim=-1).mean() + 1e-8)).item()
                        ratio_score = 1.0 / (1.0 + abs(ratio - 1.0))
                    else:
                        ratio_score = 1.0
                    scores.append(ortho_score * ratio_score if _routing == "residual_norm"
                                  else ortho_score if _routing == "residual"
                                  else ratio_score)
                routing_scores_log.append(scores)
                # Filter by threshold, then select top-k
                eligible = [(i, s) for i, s in enumerate(scores) if s >= _routing_threshold]
                if not eligible:
                    _self.no_replace_count += 1
                    return output  # no source cleared threshold — leave target unchanged
                eligible.sort(key=lambda x: x[1], reverse=True)
                k = min(_top_k if _top_k is not None else 1, len(eligible))
                selected = [i for i, _ in eligible[:k]]
                selected_source_log.append(selected)
                projected = [projected[i] for i in selected]

            # ------------------------------------------------------------------
            # Entropy routing: gate on target model confidence at graft layer.
            # If entropy < threshold the target is already confident — skip.
            # ------------------------------------------------------------------
            if _routing in ("entropy", "entropy_prototype"):
                with torch.no_grad():
                    h = activation_b
                    if _lm_norm is not None:
                        h = _lm_norm(h)
                    logits = _lm_head(h)  # [batch, vocab_size]
                    log_probs = torch.log_softmax(logits.float(), dim=-1)
                    entropy = -(torch.exp(log_probs) * log_probs).sum(dim=-1).mean().item()
                entropy_log.append(entropy)
                if entropy < _routing_threshold:
                    _self.no_replace_count += 1
                    return output  # confident → leave target unchanged
                if _routing == "entropy":
                    # No per-source selection — use all sources
                    selected_source_log.append(list(range(_n_total_sources)))
                # entropy_prototype: fall through to prototype routing block below

            # Fuse projected activations according to fusion_method
            stacked = torch.stack(projected, dim=0)  # [N, batch, d_b]

            # ------------------------------------------------------------------
            # Prototype routing: keep only the top-k sources by prototype sim.
            # This is a pre-filter step; the fusion_method then operates on the
            # selected subset only.
            # ------------------------------------------------------------------
            if prototype_sims is not None:
                k = min(_top_k if _top_k is not None else 1, _n_total_sources)
                sorted_idx = sorted(range(len(prototype_sims)), key=lambda i: prototype_sims[i], reverse=True)
                selected = sorted_idx[:k]
                selected_source_log.append(selected)
                stacked = stacked[torch.tensor(selected, device=stacked.device)]  # [k, batch, d_b]
            elif _routing not in ("residual", "norm_ratio", "residual_norm", "entropy_prototype"):
                selected_source_log.append(list(range(_n_total_sources)))

            if fusion_method == "mean":
                combined = stacked.mean(dim=0)
                weights = torch.full((stacked.shape[0],), 1.0 / stacked.shape[0])

            elif fusion_method == "norm_weighted":
                # Weight by L2 norm of each projected activation
                norms = stacked.norm(dim=-1, keepdim=True)  # [N, batch, 1]
                weights = norms / (norms.sum(dim=0, keepdim=True) + 1e-8)
                combined = (stacked * weights).sum(dim=0)

            elif fusion_method == "reverse_norm_weighted":
                # Weight inversely by L2 norm; smaller norm = higher weight
                norms = stacked.norm(dim=-1, keepdim=True)  # [N, batch, 1]
                inv_norms = 1.0 / (norms + 1e-8)
                weights = inv_norms / (inv_norms.sum(dim=0, keepdim=True) + 1e-8)
                combined = (stacked * weights).sum(dim=0)

            elif fusion_method == "similarity_weighted":
                # Weight by cosine similarity to b; more similar = more weight
                b = activation_b.unsqueeze(0)  # [1, batch, d_b]
                cos_sim = torch.nn.functional.cosine_similarity(stacked, b, dim=-1, eps=1e-8)  # [N, batch]
                weights = torch.softmax(cos_sim, dim=0).unsqueeze(-1)  # [N, batch, 1]
                combined = (stacked * weights).sum(dim=0)

            elif fusion_method == "dissimilarity_weighted":
                # Weight by (1 - cosine similarity) to b; more different = more weight
                b = activation_b.unsqueeze(0)  # [1, batch, d_b]
                cos_sim = torch.nn.functional.cosine_similarity(stacked, b, dim=-1, eps=1e-8)  # [N, batch]
                weights = torch.softmax(1.0 - cos_sim, dim=0).unsqueeze(-1)  # [N, batch, 1]
                combined = (stacked * weights).sum(dim=0)

            elif fusion_method == "orthogonal_mean":
                # Sequential Gram-Schmidt accumulation:
                #   combined  = s_0
                #             + ortho(s_1 | s_0)
                #             + ortho(s_2 | s_0, s_1)
                #             + ...
                # where ortho(s_i | s_0..s_{i-1}) removes all components of s_i
                # in the directions of the preceding source vectors.
                # Sources are processed in fixed ascending index order (0, 1, ..., N-1)
                # for reproducibility.
                N = stacked.shape[0]
                combined = stacked[0].clone()  # [batch, d_b]
                for i in range(1, N):
                    contrib = stacked[i].clone()  # [batch, d_b]
                    for j in range(i):
                        dot = (contrib * stacked[j]).sum(dim=-1, keepdim=True)       # [batch, 1]
                        norm_j_sq = stacked[j].norm(dim=-1, keepdim=True).pow(2).clamp(min=1e-8)
                        contrib = contrib - (dot / norm_j_sq) * stacked[j]
                    combined = combined + contrib
                combined = combined / N
                weights = torch.full((N,), 1.0 / N)

            elif fusion_method == "orthogonal_projection":
                # For each source, subtract its projection onto b, keeping only
                # the component orthogonal to the target activation. Average results.
                # stacked: [N, batch, d_b],  activation_b: [batch, d_b]
                b_vec = activation_b  # [batch, d_b]
                b_norm_sq = b_vec.norm(dim=-1, keepdim=True).pow(2).clamp(min=1e-8)  # [batch, 1]
                # scalar projection of each source onto b: [N, batch, 1]
                scalar_proj = (stacked * b_vec.unsqueeze(0)).sum(dim=-1, keepdim=True) / b_norm_sq
                orthogonal = stacked - scalar_proj * b_vec.unsqueeze(0)  # [N, batch, d_b]
                combined = orthogonal.mean(dim=0)  # [batch, d_b]
                weights = torch.full((stacked.shape[0],), 1.0 / stacked.shape[0])

            # Log per-source weights for this example: average over batch dim -> [N]
            if weights.dim() == 3:  # [N, batch, 1]
                weight_log.append(weights.mean(dim=(1, 2)).detach().cpu())
            else:  # already [N] (mean case)
                weight_log.append(weights.detach().cpu())

            # Log cosine similarity, L2 distance, and norms
            cosine_sim_log.append(
                torch.nn.functional.cosine_similarity(
                    combined.flatten(), activation_b.flatten(), dim=0, eps=1e-8
                ).item()
            )
            l2_dist_log.append((combined - activation_b).norm().item())
            source_norm_log.append(combined.norm().item())
            target_norm_log.append(activation_b.norm().item())

            # In dry_run mode: log diagnostics but leave hidden states untouched
            if dry_run:
                return output

            hidden_states = hidden_states.clone()
            if combination == "sum":
                hidden_states[:, pos, :] = activation_b + combined
            else:  # "replace"
                hidden_states[:, pos, :] = combined

            return repack_hook_output(hidden_states, rest)

        return hook

    def generate(
        self,
        prompts_a: List[str],
        prompt_b: str,
        max_new_tokens: int = 50,
        **generation_kwargs,
    ) -> str:
        """
        Generate text with multi-source activation grafting.

        Args:
            prompts_a: One prompt per source model (typically the same question
                       formatted with each source model's chat template)
            prompt_b: Prompt for the target model
            max_new_tokens: Maximum tokens to generate
            **generation_kwargs: Additional args for model.generate()

        Returns:
            Generated text from the target model
        """
        # Extract activations from all source models
        source_activations = self._extract_from_sources(prompts_a)

        # Prototype routing: compute per-example similarity to each prototype
        prototype_sims: Optional[List[float]] = None
        if self.prototypes is not None:
            prototype_sims = self._compute_prototype_similarities(source_activations)
            self.prototype_sim_log.append(prototype_sims)

        # Tokenize for target model
        inputs_b = self.tokenizer_b(
            prompt_b,
            return_tensors="pt",
            truncation=True,
        ).to(self.device)

        gen_kwargs = {
            "max_new_tokens": max_new_tokens,
            "pad_token_id": self.tokenizer_b.pad_token_id or self.tokenizer_b.eos_token_id,
            "do_sample": False,
        }
        gen_kwargs.update(generation_kwargs)

        # Register hook at target layer
        hook = self._create_multisource_hook(
            source_activations,
            self.graft_position,
            prototype_sims=prototype_sims,
            top_k=self.top_k,
        )
        target_layer = get_transformer_layers(self.model_b)[self.layer_b]
        hook_handle = target_layer.register_forward_hook(hook)

        try:
            with torch.no_grad():
                outputs = self.model_b.generate(**inputs_b, **gen_kwargs)
        finally:
            hook_handle.remove()

        # Decode only newly generated tokens
        generated_ids = outputs[0][inputs_b["input_ids"].shape[1]:]
        return self.tokenizer_b.decode(generated_ids, skip_special_tokens=True)

    def generate_baseline(
        self,
        prompt_b: str,
        max_new_tokens: int = 50,
        **generation_kwargs,
    ) -> str:
        """Generate from target model without grafting (baseline)."""
        return generate_response(
            self.model_b, self.tokenizer_b, prompt_b,
            max_new_tokens, self.device, **generation_kwargs,
        )


if __name__ == "__main__":
    print("Activation grafting engine module loaded successfully.")
